#load("@rules_cc//cc:cc_include.bzl", "cc_include")
#load("@rules_cc//cc:defs.bzl", "cc_library")
#cc_include(
#    name = "include_name",
#    hdrs = ["testInc.h"],
#    #visibility = ["//source:__pkg__"],
#    visibility = ["//visibility:public"],
#)

#cc_library(
#    name = "include_name",
#    hdrs = ["testInc.h"],
#    visibility = ["//visibility:public"], # Allows other packages to depend on this library
#)

