name: CI for docker/build-push-action
on:
  push:
    branches:
      - main
permissions:
      contents: write # Only allow reading of repository contents
      issues: write # Allow writing to issues
      pull-requests: write # Allow writing to pull requests
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
        contents: write # This job needs write access to contents
        pull-requests: read # This job only needs read access to pull requests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMG_NAME }}:v8