name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]


jobs:
  bash-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Bash script
        run: bash run.sh < input.txt
